name: CI Pipeline

on:
  push:
    branches: ["main", "wahab"]
  pull_request:
    branches: ["main"]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Basic validation
        run: |
          echo "CI is running on branch wahab"
          test -f README.md
